import { text, timestamp } from "drizzle-orm/pg-core";
import { uuidv7 } from "../../ids.js";

/** `created_at` / `updated_at` on every table (05 §1). */
export const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};

/** Text primary key holding a UUID v7, generated by the engine. */
export const idPk = () => text("id").primaryKey().$defaultFn(() => uuidv7());

export const tstz = (name: string) => timestamp(name, { withTimezone: true });
