import { integer, pgTable, text, uniqueIndex } from "drizzle-orm/pg-core";
import { idPk, timestamps } from "./_common.js";
import { projects } from "./projects.js";

/** AES-256-GCM with FORJA_MASTER_KEY; the plaintext value is never stored or returned. */
export const secrets = pgTable(
  "secrets",
  {
    id: idPk(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    /** development | production | both */
    environment: text("environment").notNull().default("both"),
    /** user | system (generated by the engine, e.g. DB passwords) */
    kind: text("kind").notNull().default("user"),
    /** base64 */
    ciphertext: text("ciphertext").notNull(),
    /** base64 */
    nonce: text("nonce").notNull(),
    keyVersion: integer("key_version").notNull().default(1),
    ...timestamps,
  },
  (t) => [uniqueIndex("secrets_project_name_env_uq").on(t.projectId, t.name, t.environment)],
);
