/**
 * Applies the SQL migrations in apps/engine/drizzle/ (generated by `npm run db:generate`).
 *
 * ⭐ Runs at every engine boot under a Postgres advisory lock held on one reserved
 * connection, so several engine instances starting together migrate exactly once.
 * Also runnable standalone: `npm run db:migrate -w @forja/engine`.
 */
import { fileURLToPath, pathToFileURL } from "node:url";
import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres, { type Sql } from "postgres";
import type { Logger } from "../logger.js";

/** Same relative path from src/db/ and dist/db/. */
export const MIGRATIONS_DIR = fileURLToPath(new URL("../../drizzle", import.meta.url));

/** Arbitrary constant; `pg_advisory_lock(bigint)`. "forja" in ASCII. */
const MIGRATION_LOCK_ID = 0x666f726a61n;

/**
 * Opens its own single-connection client (`max: 1`) so the advisory lock and every
 * migration statement run on the same session; drizzle cannot wrap a reserved connection.
 */
export async function runMigrations(databaseUrl: string, logger: Pick<Logger, "info">): Promise<void> {
  const sql: Sql = postgres(databaseUrl, { max: 1, onnotice: () => {} });
  try {
    await sql`select pg_advisory_lock(${MIGRATION_LOCK_ID.toString()}::bigint)`;
    try {
      const started = Date.now();
      await migrate(drizzle(sql), { migrationsFolder: MIGRATIONS_DIR });
      logger.info({ ms: Date.now() - started }, "database migrations applied");
    } finally {
      await sql`select pg_advisory_unlock(${MIGRATION_LOCK_ID.toString()}::bigint)`;
    }
  } finally {
    await sql.end({ timeout: 5 });
  }
}

const invokedDirectly =
  process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;

if (invokedDirectly) {
  const { loadConfig } = await import("../config.js");
  const { createLogger } = await import("../logger.js");
  const config = loadConfig();
  const logger = createLogger({ level: config.LOG_LEVEL });
  try {
    await runMigrations(config.DATABASE_URL, logger);
  } catch (err) {
    logger.error({ err }, "migration failed");
    process.exitCode = 1;
  }
}
