/**
 * Applies the SQL migrations in apps/engine/drizzle/ (generated by `npm run db:generate`).
 *
 * ⭐ Runs at every engine boot under a Postgres advisory lock held on one reserved
 * connection, so several engine instances starting together migrate exactly once.
 * Also runnable standalone: `npm run db:migrate -w @forja/engine` (src/migrate-cli.ts).
 */
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres, { type Sql } from "postgres";
import type { Logger } from "../logger.js";

/**
 * apps/engine/drizzle, found from wherever this code runs: `src/db/migrate.ts` (tsx, tests)
 * or the esbuild bundle `dist/index.js` / `dist/migrate.js`.
 */
export const MIGRATIONS_DIR = ((): string => {
  const candidates = ["../../drizzle", "../drizzle"].map((rel) => fileURLToPath(new URL(rel, import.meta.url)));
  return candidates.find((dir) => existsSync(`${dir}/meta/_journal.json`)) ?? (candidates[0] as string);
})();

/** Arbitrary constant; `pg_advisory_lock(bigint)`. "forja" in ASCII. */
const MIGRATION_LOCK_ID = 0x666f726a61n;

/**
 * Opens its own single-connection client (`max: 1`) so the advisory lock and every
 * migration statement run on the same session; drizzle cannot wrap a reserved connection.
 */
export async function runMigrations(databaseUrl: string, logger: Pick<Logger, "info">): Promise<void> {
  const sql: Sql = postgres(databaseUrl, { max: 1, onnotice: () => {} });
  try {
    await sql`select pg_advisory_lock(${MIGRATION_LOCK_ID.toString()}::bigint)`;
    try {
      const started = Date.now();
      await migrate(drizzle(sql), { migrationsFolder: MIGRATIONS_DIR });
      logger.info({ ms: Date.now() - started }, "database migrations applied");
    } finally {
      await sql`select pg_advisory_unlock(${MIGRATION_LOCK_ID.toString()}::bigint)`;
    }
  } finally {
    await sql.end({ timeout: 5 });
  }
}
