/**
 * Project secrets (05 §1, 07 §2).
 *
 * Protects:
 * - Values are AES-256-GCM encrypted with a key DERIVED from `FORJA_MASTER_KEY` (HMAC with a
 *   fixed label, so the master key is never used directly for two purposes; the signed-URL
 *   surface derives its own). `key_version` = 1 until `secrets:rotate` exists.
 * - The AAD binds each ciphertext to `projectId/name/environment`: a row copied onto another
 *   project or name does not decrypt.
 * - No API shape ever carries a value back (`toApi` returns name and scope only).
 * - `system` secrets (DB passwords, BETTER_AUTH_SECRET) are generated by the engine, are not
 *   listed on the project and cannot be deleted through the API.
 * - Rendering for a container returns a plain record for the Docker create call's `Env`
 *   (Docker's API has no env_file; nothing is written into the worktree).
 */
import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes } from "node:crypto";
import type { SecretRow, Store } from "../store/types.js";

export const SECRET_KEY_VERSION = 1;
const LABEL = "forja:secrets:v1";

/** System secrets the engine generates per project. */
export const SYSTEM_SECRETS = {
  dbSuperuser: "FORJA_DB_SUPERUSER_PASSWORD",
  dbAppRw: "FORJA_DB_APP_RW_PASSWORD",
  dbCmsRo: "FORJA_DB_CMS_RO_PASSWORD",
  dbCmsRw: "FORJA_DB_CMS_RW_PASSWORD",
  betterAuth: "BETTER_AUTH_SECRET",
} as const;

/** Variables the engine owns in the sandbox env; a user secret may not use these names. */
export const RESERVED_SECRET_NAMES: ReadonlySet<string> = new Set([
  ...Object.values(SYSTEM_SECRETS),
  "DATABASE_URL",
  "NEXT_PUBLIC_APP_URL",
  "INTERNAL_APP_URL",
  "ALLOWED_FRAME_ANCESTORS",
  "HOME",
  "PORT",
  "HOSTNAME",
  "NODE_ENV",
  "PATH",
  "NEXT_TELEMETRY_DISABLED",
  "FORJA_RUN_ID",
]);

export const SECRET_NAME_RE = /^[A-Za-z_][A-Za-z0-9_]{0,127}$/;

export type SecretEnvironment = "development" | "production" | "both";

export class SecretBox {
  private readonly key: Buffer;
  constructor(masterKeyBase64: string) {
    this.key = createHmac("sha256", Buffer.from(masterKeyBase64, "base64")).update(LABEL).digest();
  }

  private static aad(projectId: string, name: string, environment: string): Buffer {
    return Buffer.from(`${projectId}\0${name}\0${environment}`);
  }

  seal(projectId: string, name: string, environment: string, value: string): { ciphertext: string; nonce: string; keyVersion: number } {
    const nonce = randomBytes(12);
    const cipher = createCipheriv("aes-256-gcm", this.key, nonce);
    cipher.setAAD(SecretBox.aad(projectId, name, environment));
    const enc = Buffer.concat([cipher.update(value, "utf8"), cipher.final(), cipher.getAuthTag()]);
    return { ciphertext: enc.toString("base64"), nonce: nonce.toString("base64"), keyVersion: SECRET_KEY_VERSION };
  }

  open(row: Pick<SecretRow, "projectId" | "name" | "environment" | "ciphertext" | "nonce">): string {
    const data = Buffer.from(row.ciphertext, "base64");
    if (data.length < 16) throw new Error("ciphertext too short");
    const decipher = createDecipheriv("aes-256-gcm", this.key, Buffer.from(row.nonce, "base64"));
    decipher.setAAD(SecretBox.aad(row.projectId, row.name, row.environment));
    decipher.setAuthTag(data.subarray(data.length - 16));
    return Buffer.concat([decipher.update(data.subarray(0, data.length - 16)), decipher.final()]).toString("utf8");
  }
}

export function generateSecretValue(bytes = 24): string {
  return randomBytes(bytes).toString("base64url");
}

export class SecretsService {
  constructor(
    private readonly store: Store,
    private readonly box: SecretBox,
  ) {}

  /** What `project.secrets` lists: user secrets, name and scope only. */
  async listForApi(projectId: string): Promise<{ _id: string; secretName: string; environment: SecretEnvironment }[]> {
    const rows = await this.store.listSecrets(projectId, "user");
    return rows.map((r) => ({ _id: r.id, secretName: r.name, environment: r.environment as SecretEnvironment }));
  }

  async setUser(projectId: string, name: string, environment: SecretEnvironment, value: string): Promise<SecretRow> {
    return this.store.upsertSecret({ projectId, name, environment, kind: "user", ...this.box.seal(projectId, name, environment, value) });
  }

  deleteUser(projectId: string, id: string): Promise<boolean> {
    return this.store.deleteSecret(projectId, id, "user");
  }

  /** Reads the system secret, generating and storing it on first use. */
  async ensureSystem(projectId: string, name: string, generate: () => string = () => generateSecretValue()): Promise<string> {
    const rows = await this.store.listSecrets(projectId, "system");
    const row = rows.find((r) => r.name === name && r.environment === "development");
    if (row) return this.box.open(row);
    const value = generate();
    await this.store.upsertSecret({
      projectId,
      name,
      environment: "development",
      kind: "system",
      ...this.box.seal(projectId, name, "development", value),
    });
    return value;
  }

  /** User secrets for one environment (`both` applies to each), decrypted. */
  async renderUser(projectId: string, environment: "development" | "production"): Promise<Record<string, string>> {
    const rows = await this.store.listSecrets(projectId, "user");
    const out: Record<string, string> = {};
    // `both` first so an environment-specific value of the same name wins.
    for (const r of rows.filter((x) => x.environment === "both")) out[r.name] = this.box.open(r);
    for (const r of rows.filter((x) => x.environment === environment)) out[r.name] = this.box.open(r);
    return out;
  }
}

/** Stable hash of a rendered env (key order independent): a rebuild compares it. */
export function envHash(env: Record<string, string>): string {
  const sorted = Object.keys(env)
    .sort()
    .map((k) => [k, env[k]]);
  return createHash("sha256").update(JSON.stringify(sorted)).digest("hex");
}

/** dotenv text for an env record (used by `github/env` with ALLOW_ENV_EXPORT, and logs never). */
export function toDotenv(env: Record<string, string>, mask = false): string {
  return Object.entries(env)
    .map(([k, v]) => `${k}=${mask ? "***" : JSON.stringify(v)}`)
    .join("\n");
}
